os: linux
dist: bionic
language: java
jdk:
  - openjdk8
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew check
  - cd examples && ./gradlew check && cd ..

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

after_failure: dmesg -T | grep -E -i -B100 'killed process'

before_deploy:
  - openssl aes-256-cbc -K $encrypted_6afd0fc9428e_key -iv $encrypted_6afd0fc9428e_iv
    -in secring.gpg.enc -out $TRAVIS_BUILD_DIR/secring.gpg -d

deploy:
- provider: script
  skip_cleanup: true
  script: ./gradlew --no-parallel publishToSonatype uploadDocs publishPlugins closeAndReleaseRepository -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=$TRAVIS_BUILD_DIR/secring.gpg -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  on:
    tags: true
    jdk: openjdk11
- provider: script
  skip_cleanup: true
  script: ./gradlew uploadDocs
  on:
    tags: false
    jdk: openjdk11
