name: Publish to MavenCentral and plugins.gradle.org

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - run: gpg --quiet --batch --yes --decrypt --passphrase="$PASS" --output=secring.gpg secring.gpg.gpg
        env:
          PASS: ${{ secrets.FREEFAIR_SECRING_PASS }}
      - name: Publish package
        run: ./gradlew --no-parallel publishToSonatype publishPlugins uploadDocs closeAndReleaseRepository -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/secring.gpg
        env:
          ORG_GRADLE_PROJECT_ossrhUser: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPass: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.FREEFAIR_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.FREEFAIR_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_freefairDocsUser: ${{ secrets.FREEFAIR_DOCS_USER }}
          ORG_GRADLE_PROJECT_freefairDocsPass: ${{ secrets.FREEFAIR_DOCS_PASS }}
